<b>Regression Task</b><br>
Use the given dataset and perform the following:-
<ol>
<li> Read the 'heat_load.xlsx' dataset.</li>
<li> Rename the columns as per the given features</li> 
<li> Remove/handle null values if any</li>    
<li> Considering all the features as independent features (except heating and cooling load) Split the dataset into training and test dataset with test_size = 25%</li>
<li> Predict the Heating load based on features from X1 to X8 and also calculate
the model score. Also find the intercept and the coefficients corresponding to
each of these features. Generate equation of Linear regression</li>
<li>Predict the Cooling load based on features from X1 to X8 and also calculate
the model score. Also find the intercept and the coefficients corresponding 
to each of these features. Generate equation of Linear regression</li>
<li> Compute MSE, MAE, RMSE for two scenarios(5 and 6)</li> 
<li>Select appropriate independent features based on Correlation matrix</li>
<li>Repeat Q5 and Q7 for heating load after the original dataset has been split into training and testing dataset with test_size=25% with appropriate independent features selected from correlation matrix</li>
<li>Repeat Q6 and Q7 for cooling load after the original dataset has been split into training and testing dataset with test_size=25% with appropriate independent features selected from correlation matrix</li>   
</ol>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_excel('heat_load.xlsx')
df.head()

X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28

In [ ]:
"""
X1 - Relative Compactness
X2 - Surface Area
X3 - Wall Area
X4 - Roof Area
X5 - Overall Height
X6 - Orientation
X7 - Glazing Area
X8 - Glazing Area Distrbution
Y1 - Heating Load
Y2 - Cooling Load


"""

'\nX1 - Relative Compactness\nX2 - Surface Area\nX3 - Wall Area\nX4 - Roof Area\nX5 - Overall Height\nX6 - Orientation\nX7 - Glazing Area\nX8 - Glazing Area Distrbution\nY1 - Heating Load\nY2 - Cooling Load\n\n\n'

In [ ]:
df.columns= ['compact','s_area','w_area','r_area','height','orient',
             'g_area','g_area_dist','heat_load','cool_load']
df.head()

compact  s_area  w_area  r_area  height  orient  g_area  g_area_dist  \
0     0.98   514.5   294.0  110.25     7.0       2     0.0            0   
1     0.98   514.5   294.0  110.25     7.0       3     0.0            0   
2     0.98   514.5   294.0  110.25     7.0       4     0.0            0   
3     0.98   514.5   294.0  110.25     7.0       5     0.0            0   
4     0.90   563.5   318.5  122.50     7.0       2     0.0            0   

   heat_load  cool_load  
0      15.55      21.33  
1      15.55      21.33  
2      15.55      21.33  
3      15.55      21.33  
4      20.84      28.28

In [ ]:
df.shape

(768, 10)

In [ ]:
df.isnull().sum()

compact        0
s_area         0
w_area         0
r_area         0
height         0
orient         0
g_area         0
g_area_dist    0
heat_load      0
cool_load      0
dtype: int64

In [ ]:
df.head(2)

compact  s_area  w_area  r_area  height  orient  g_area  g_area_dist  \
0     0.98   514.5   294.0  110.25     7.0       2     0.0            0   
1     0.98   514.5   294.0  110.25     7.0       3     0.0            0   

   heat_load  cool_load  
0      15.55      21.33  
1      15.55      21.33

### Prediction of Heating Load

In [ ]:
x = df.iloc[:,:-2] # X1-X8
y = df.iloc[:,-2]  # heating load
print(x.shape)
print(y.shape)

(768, 8)
(768,)


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(576, 8)
(192, 8)
(576,)
(192,)


In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
reg = LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [ ]:
reg.score(x_train,y_train)

0.9179948432596498

In [ ]:
reg.score(x_test,y_test)

0.90955065084125

In [ ]:
y_pred = reg.predict(x_test)
len(y_test)

192

In [ ]:
reg.coef_

array([-6.39361840e+01,  5.78749541e+10, -5.78749541e+10, -1.15749908e+11,
        4.19577563e+00, -5.93708083e-03,  1.91078568e+01,  2.06867015e-01])

In [ ]:
reg.intercept_

83.04353310243103

In [ ]:
# df2 = pd.DataFrame({'y_orig':y_test,'y_pred':y_pred})
# df2.head(10)

In [ ]:
df.columns

Index(['compact', 's_area', 'w_area', 'r_area', 'height', 'orient', 'g_area',
       'g_area_dist', 'heat_load', 'cool_load'],
      dtype='object')

In [ ]:
x_test['y_true'] = y_test
x_test['y_pred'] = y_pred
x_test.head()

E:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
E:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


compact  s_area  w_area  r_area  height  orient  g_area  g_area_dist  \
539     0.86   588.0   294.0  147.00     7.0       5    0.40            1   
416     0.69   735.0   294.0  220.50     3.5       2    0.25            3   
116     0.76   661.5   416.5  122.50     7.0       2    0.10            2   
242     0.98   514.5   294.0  110.25     7.0       4    0.10            5   
226     0.69   735.0   294.0  220.50     3.5       4    0.10            4   

     y_true     y_pred  
539   31.29  32.089756  
416   12.34  13.188658  
116   33.16  33.914108  
242   24.03  25.843147  
226   11.07  10.517472

In [ ]:
### Eqn 
x_test['HeatLoad_pred_eqn'] = x_test['compact']*reg.coef_[0] + \
                x_test['s_area']*reg.coef_[1] + \
                x_test['w_area']*reg.coef_[2] + x_test['r_area']*reg.coef_[3] + \
                x_test['height']*reg.coef_[4] + x_test['orient']*reg.coef_[5] + \
                x_test['g_area']*reg.coef_[6] + x_test['g_area_dist']*reg.coef_[7] +\
                reg.intercept_
x_test.head()

E:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


compact  s_area  w_area  r_area  height  orient  g_area  g_area_dist  \
539     0.86   588.0   294.0  147.00     7.0       5    0.40            1   
416     0.69   735.0   294.0  220.50     3.5       2    0.25            3   
116     0.76   661.5   416.5  122.50     7.0       2    0.10            2   
242     0.98   514.5   294.0  110.25     7.0       4    0.10            5   
226     0.69   735.0   294.0  220.50     3.5       4    0.10            4   

     y_true     y_pred  HeatLoad_pred_eqn  
539   31.29  32.089756          32.089756  
416   12.34  13.188658          13.188658  
116   33.16  33.914108          33.912155  
242   24.03  25.843147          25.843147  
226   11.07  10.517472          10.517472

In [ ]:
# df2['SSE'] = (df2['y_orig'] - df2['y_pred'])**2
# df2.head()

In [ ]:
# print(df2.sum())
# print('-----------')
# print(df2.sum()/192)

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [ ]:
mse = mean_squared_error(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = mse**0.5
print('MSE',mse)
print('MAE',mae)
print('RMSE',rmse)

MSE 9.908146240017183
MAE 2.2415832086530614
RMSE 3.1477208008362467


### Prediction of Cooling Load

In [ ]:
x1 = df.iloc[:,:-2] # X1-X8
y1 = df.iloc[:,-1] # cooling load
print(x1.shape)
print(y1.shape)

(768, 8)
(768,)


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x1,y1,test_size=0.25)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(576, 8)
(192, 8)
(576,)
(192,)


In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
reg1 = LinearRegression()
reg1.fit(x_train,y_train)

LinearRegression()

In [ ]:
reg1.score(x_train,y_train)

0.8854269821567536

In [ ]:
reg1.score(x_test,y_test)

0.890740243398294

In [ ]:
y_pred = reg1.predict(x_test)
len(y_test)

192

In [ ]:
print(type(y_pred))
y_pred[:5]

<class 'numpy.ndarray'>


array([33.49000429, 14.71138807, 15.36863765, 15.19389325, 13.36808874])

In [ ]:
reg1.coef_

array([-6.64071755e+01, -2.03645205e+11,  2.03645205e+11,  4.07290411e+11,
        4.38537335e+00,  8.73722024e-02,  1.54268864e+01,  7.61413798e-02])

In [ ]:
reg1.intercept_

89.07110432568801

In [ ]:
# df3 = pd.DataFrame({'y_orig':y_test,'y_pred':y_pred})
# df3.head(10)

In [ ]:
x_test['y_true'] = y_test
x_test['y_pred'] = y_pred
x_test.head()

E:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
E:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


compact  s_area  w_area  r_area  height  orient  g_area  g_area_dist  \
303     0.82   612.5   318.5   147.0     7.0       5    0.25            1   
507     0.74   686.0   245.0   220.5     3.5       5    0.25            5   
190     0.62   808.5   367.5   220.5     3.5       4    0.10            3   
188     0.62   808.5   367.5   220.5     3.5       2    0.10            3   
223     0.71   710.5   269.5   220.5     3.5       5    0.10            4   

     y_true     y_pred  
303   31.39  33.490004  
507   14.03  14.711388  
190   14.14  15.368638  
188   14.09  15.193893  
223   14.20  13.368089

In [ ]:
### Eqn 
x_test['CoolLoad_pred_eqn'] = x_test['compact']*reg1.coef_[0] + \
                x_test['s_area']*reg1.coef_[1] + \
                x_test['w_area']*reg1.coef_[2] + x_test['r_area']*reg1.coef_[3] + \
                x_test['height']*reg1.coef_[4] + x_test['orient']*reg1.coef_[5] + \
                x_test['g_area']*reg1.coef_[6] + x_test['g_area_dist']*reg1.coef_[7] +\
                reg1.intercept_
x_test.head()

E:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


compact  s_area  w_area  r_area  height  orient  g_area  g_area_dist  \
303     0.82   612.5   318.5   147.0     7.0       5    0.25            1   
507     0.74   686.0   245.0   220.5     3.5       5    0.25            5   
190     0.62   808.5   367.5   220.5     3.5       4    0.10            3   
188     0.62   808.5   367.5   220.5     3.5       2    0.10            3   
223     0.71   710.5   269.5   220.5     3.5       5    0.10            4   

     y_true     y_pred  CoolLoad_pred_eqn  
303   31.39  33.490004          33.497817  
507   14.03  14.711388          14.719201  
190   14.14  15.368638          15.353013  
188   14.09  15.193893          15.178268  
223   14.20  13.368089          13.375901

In [ ]:
# df3['SSE'] = (df3['y_orig'] - df3['y_pred'])**2
# df3.head()

In [ ]:
# df3.sum()

In [ ]:
mse = mean_squared_error(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = mse**0.5
print('MSE',mse)
print('MAE',mae)
print('RMSE',rmse)

MSE 9.740073221134088
MAE 2.175515486655336
RMSE 3.1209090376257502


### Feature Selection based on Correlation

#### Predicting heating load

In [ ]:
df.corr()

compact        s_area        w_area        r_area  \
compact      1.000000e+00 -9.919015e-01 -2.037817e-01 -8.688234e-01   
s_area      -9.919015e-01  1.000000e+00  1.955016e-01  8.807195e-01   
w_area      -2.037817e-01  1.955016e-01  1.000000e+00 -2.923165e-01   
r_area      -8.688234e-01  8.807195e-01 -2.923165e-01  1.000000e+00   
height       8.277473e-01 -8.581477e-01  2.809757e-01 -9.725122e-01   
orient       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
g_area       1.283986e-17  1.318356e-16 -7.969726e-19 -1.381805e-16   
g_area_dist  1.764620e-17 -3.558613e-16  0.000000e+00 -1.079129e-16   
heat_load    6.222719e-01 -6.581199e-01  4.556714e-01 -8.618281e-01   
cool_load    6.343391e-01 -6.729989e-01  4.271170e-01 -8.625466e-01   

                   height    orient        g_area   g_area_dist  heat_load  \
compact      8.277473e-01  0.000000  1.283986e-17  1.764620e-17   0.622272   
s_area      -8.581477e-01  0.000000  1.318356e-16 -3.558613e-16  -0.658120   
w_area       2.809757e-01  0.000000 -7.969726e-19  0.000000e+00   0.455671   
r_area      -9.725122e-01  0.000000 -1.381805e-16 -1.079129e-16  -0.861828   
height       1.000000e+00  0.000000  1.861418e-18  0.000000e+00   0.889430   
orient       0.000000e+00  1.000000  0.000000e+00  0.000000e+00  -0.002587   
g_area       1.861418e-18  0.000000  1.000000e+00  2.129642e-01   0.269842   
g_area_dist  0.000000e+00  0.000000  2.129642e-01  1.000000e+00   0.087368   
heat_load    8.894305e-01 -0.002587  2.698417e-01  8.736846e-02   1.000000   
cool_load    8.957852e-01  0.014290  2.075050e-01  5.052512e-02   0.975862   

             cool_load  
compact       0.634339  
s_area       -0.672999  
w_area        0.427117  
r_area       -0.862547  
height        0.895785  
orient        0.014290  
g_area        0.207505  
g_area_dist   0.050525  
heat_load     0.975862  
cool_load     1.000000

In [ ]:
x1 = df.iloc[:,[0,2,4,6,7]]
y1 = df.iloc[:,-2]
print(x1.shape)
print(y1.shape)

(768, 5)
(768,)


In [ ]:
x1.head(2)

compact  w_area  height  g_area  g_area_dist
0     0.98   294.0     7.0     0.0            0
1     0.98   294.0     7.0     0.0            0

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x1,y1,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(576, 5)
(192, 5)
(576,)
(192,)


In [ ]:
reg_heat = LinearRegression()
reg_heat.fit(x_train,y_train)

LinearRegression()

In [ ]:
print(reg_heat.score(x_train,y_train))
print(reg_heat.score(x_test,y_test))

0.9164778316348885
0.9025093296656446


In [ ]:
y_pred_heat = reg_heat.predict(x_test)
# y_pred_heat

In [ ]:
# print(reg_heat.coef_)
a = reg_heat.coef_
print(a)
print(reg_heat.intercept_)

[-13.19425864   0.03530392   5.54453579  19.11495515   0.18754119]
-12.917454151730887


In [ ]:
x_test['y_test'] = y_test
x_test['y_pred'] = y_pred_heat
x_test.head()

E:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
E:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


compact  w_area  height  g_area  g_area_dist  y_test     y_pred
516     0.66   318.5     3.5    0.25            5   12.93  14.740955
427     0.64   343.0     3.5    0.25            3   16.86  15.494704
429     0.62   367.5     3.5    0.25            3   14.34  16.623535
104     0.86   294.0     7.0    0.10            2   26.48  27.213165
736     0.79   343.0     7.0    0.40            5   42.11  36.163766

In [ ]:
print(a) # reg_heat.coef_

[-13.19425864   0.03530392   5.54453579  19.11495515   0.18754119]


In [ ]:
### Eqn 
x_test['HeatLoad_pred_eqn'] = x_test['compact']*a[0] + \
                x_test['w_area']*a[1] + x_test['height']*a[2] + \
                x_test['g_area']*a[3] + x_test['g_area_dist']*a[4] +\
                reg_heat.intercept_
x_test.head()

E:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


compact  w_area  height  g_area  g_area_dist  y_test     y_pred  \
516     0.66   318.5     3.5    0.25            5   12.93  14.740955   
427     0.64   343.0     3.5    0.25            3   16.86  15.494704   
429     0.62   367.5     3.5    0.25            3   14.34  16.623535   
104     0.86   294.0     7.0    0.10            2   26.48  27.213165   
736     0.79   343.0     7.0    0.40            5   42.11  36.163766   

     HeatLoad_pred_eqn  
516          14.740955  
427          15.494704  
429          16.623535  
104          27.213165  
736          36.163766

In [ ]:
mse = mean_squared_error(y_test,y_pred_heat)
mae = mean_absolute_error(y_test,y_pred_heat)
rmse = mse**0.5
print('MSE',mse)
print('MAE',mae)
print('RMSE',rmse)

MSE 9.667731142376889
MAE 2.1991537205409544
RMSE 3.109297531979995


#### Predicting cooling load

In [ ]:
df.corr()

compact        s_area        w_area        r_area  \
compact      1.000000e+00 -9.919015e-01 -2.037817e-01 -8.688234e-01   
s_area      -9.919015e-01  1.000000e+00  1.955016e-01  8.807195e-01   
w_area      -2.037817e-01  1.955016e-01  1.000000e+00 -2.923165e-01   
r_area      -8.688234e-01  8.807195e-01 -2.923165e-01  1.000000e+00   
height       8.277473e-01 -8.581477e-01  2.809757e-01 -9.725122e-01   
orient       0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
g_area       1.283986e-17  1.318356e-16 -7.969726e-19 -1.381805e-16   
g_area_dist  1.764620e-17 -3.558613e-16  0.000000e+00 -1.079129e-16   
heat_load    6.222719e-01 -6.581199e-01  4.556714e-01 -8.618281e-01   
cool_load    6.343391e-01 -6.729989e-01  4.271170e-01 -8.625466e-01   

                   height    orient        g_area   g_area_dist  heat_load  \
compact      8.277473e-01  0.000000  1.283986e-17  1.764620e-17   0.622272   
s_area      -8.581477e-01  0.000000  1.318356e-16 -3.558613e-16  -0.658120   
w_area       2.809757e-01  0.000000 -7.969726e-19  0.000000e+00   0.455671   
r_area      -9.725122e-01  0.000000 -1.381805e-16 -1.079129e-16  -0.861828   
height       1.000000e+00  0.000000  1.861418e-18  0.000000e+00   0.889430   
orient       0.000000e+00  1.000000  0.000000e+00  0.000000e+00  -0.002587   
g_area       1.861418e-18  0.000000  1.000000e+00  2.129642e-01   0.269842   
g_area_dist  0.000000e+00  0.000000  2.129642e-01  1.000000e+00   0.087368   
heat_load    8.894305e-01 -0.002587  2.698417e-01  8.736846e-02   1.000000   
cool_load    8.957852e-01  0.014290  2.075050e-01  5.052512e-02   0.975862   

             cool_load  
compact       0.634339  
s_area       -0.672999  
w_area        0.427117  
r_area       -0.862547  
height        0.895785  
orient        0.014290  
g_area        0.207505  
g_area_dist   0.050525  
heat_load     0.975862  
cool_load     1.000000

In [ ]:
x2 = df.iloc[:,[0,2,4,5,6,7]]
y2 = df.iloc[:,-1]
print(x2.shape)
print(y2.shape)

(768, 6)
(768,)


In [ ]:
x2.head(2)

compact  w_area  height  orient  g_area  g_area_dist
0     0.98   294.0     7.0       2     0.0            0
1     0.98   294.0     7.0       3     0.0            0

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x2,y2,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(576, 6)
(192, 6)
(576,)
(192,)


In [ ]:
reg_cool = LinearRegression()
reg_cool.fit(x_train,y_train)

LinearRegression()

In [ ]:
print(reg_cool.score(x_train,y_train))
print(reg_cool.score(x_test,y_test))


0.8839097166718051
0.8840867110562004


In [ ]:
y_pred_cool = reg_cool.predict(x_test)

In [ ]:
coef = reg_cool.coef_
intercept = reg_cool.intercept_
print(coef)
print(intercept)

[-15.75991271   0.02253102   5.45155973   0.03378287  14.51379377
   0.07007549]
-2.942683976308558


In [ ]:
x_test['y_test'] = y_test
x_test['y_pred'] = y_pred_cool
x_test.head()

E:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
E:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


compact  w_area  height  orient  g_area  g_area_dist  y_test     y_pred
270     0.71   269.5     3.5       4     0.1            5   14.26  12.957235
574     0.62   367.5     3.5       4     0.4            1   17.15  20.657503
217     0.74   245.0     3.5       3     0.1            4   13.36  11.828569
280     0.64   343.0     3.5       2     0.1            5   19.24  15.648893
727     0.90   318.5     7.0       5     0.4            5   37.27  34.535252

In [ ]:
### Eqn 
x_test['CoolLoad_pred_eqn'] = x_test['compact']*coef[0] + \
                x_test['w_area']*coef[1] + x_test['height']*coef[2] + \
                x_test['orient']*coef[3] + x_test['g_area']*coef[4] + \
                x_test['g_area_dist']*coef[5] + intercept
x_test.head()

E:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


compact  w_area  height  orient  g_area  g_area_dist  y_test     y_pred  \
270     0.71   269.5     3.5       4     0.1            5   14.26  12.957235   
574     0.62   367.5     3.5       4     0.4            1   17.15  20.657503   
217     0.74   245.0     3.5       3     0.1            4   13.36  11.828569   
280     0.64   343.0     3.5       2     0.1            5   19.24  15.648893   
727     0.90   318.5     7.0       5     0.4            5   37.27  34.535252   

     CoolLoad_pred_eqn  
270          12.957235  
574          20.657503  
217          11.828569  
280          15.648893  
727          34.535252

In [ ]:
mse = mean_squared_error(y_test,y_pred_cool)
mae = mean_absolute_error(y_test,y_pred_cool)
rmse = mse**0.5
print('MSE',mse)
print('MAE',mae)
print('RMSE',rmse)

MSE 11.492016380358132
MAE 2.2820044643822546
RMSE 3.389987666697053
